name: Setup CI
description: 'Sets up the CI environment'
runs:
  using: composite
  steps:
    - name: Setup Node.js Latest
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        registry-url: "https://registry.npmjs.org"
    - name: Enable Corepack and install Yarn latest
      shell: bash
      run: |
        corepack enable
        corepack prepare yarn@latest
    - name: Install dependencies
      shell: bash
      run: yarn install
