name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-setup
      - name: Build Tools
        run: yarn run build
      - name: Lint
        run: yarn run lint

  typecheck: 
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-setup
      - name: Build Tools
        run: yarn run build
      - name: Typecheck
        run: yarn run check-types

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-setup
      - name: Build Tools
        run: yarn run build
      - name: Format
        run: yarn run format

  sherif-lint:
    name: Sherif-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-setup
      - name: Build Tools
        run: yarn run build
      - name: Lint Sherif
        run: yarn run lint:ws

  ci-ok: 
    name: CI OK
    runs-on: ubuntu-latest
    if: always()
    needs: [lint, typecheck, format, sherif-lint]
    env:
      FAILURE: ${{ contains(join(needs.*.result, ','), 'failure') }}
    steps:
      - name: Check for failure
        run: |
          echo $FAILURE
          if [ "$FAILURE" = "false" ]; then
            exit 0
          else
            exit 1
          fi
